version: 0.2
phases:

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1
      - URI=public.ecr.aws/x9c0g2j1/test-doc
      - IMAGE_REPO_NAME=etools-docker
      - echo Prebuild completed...
  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker test image...
      - echo Building the Docker image...
      - docker build -t test-doc .
      - docker tag test-doc:latest public.ecr.aws/x9c0g2j1/test-doc:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/x9c0g2j1/test-doc:latest
