version: 0.2
phases:

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 675418481961.dkr.ecr.ap-south-1.amazonaws.com
      - URI=public.ecr.aws/x9c0g2j1/test-doc
      - IMAGE_REPO_NAME=etools-docker
      - echo Prebuild completed...
  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker test image...
      - echo Building the Docker image...
      - docker build -t test-docker .
      - docker tag test-docker:latest 675418481961.dkr.ecr.ap-south-1.amazonaws.com/test-docker:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 675418481961.dkr.ecr.ap-south-1.amazonaws.com/test-docker:latest
